# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose
      - name: setup wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
      - name: setup-node
        uses: actions/setup-node@v2.1.4
      - name: build webpage
        run: |
          cd www
          npm install
          npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: build_artifact
          path: www/dist/
      - name: Register doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{ secrets.DIGITALOCEAN_API }}
      - name: Download previously built artifact
      - name: Change directory
        run: cd www
      - name: Build dockerfile
        uses: ripplr-io/docr-docker-publish@v1
        with:
          image_path: registry.digitalocean.com/lobbi44/connect-four

